### PR TITLE
Add podspec

### PR DESCRIPTION
**Pull request by Ashton-W**
Following from #2

I've made the following assumptions:
- the license is ISC
- platform deployment targets in the Xcode project are correctly minimum
- the 'homepage' listed on CocoaPods.org/CLI search results is preferred to be this repo, not the blog post.
- tvOS and watchOS are not supported. If they are, something like the following can be added:
```ruby
  s.watchos.deployment_target = "3.0"
  s.tvos.deployment_target = "10.0"
```

After merging this you will need to [push to trunk](https://guides.cocoapods.org/making/getting-setup-with-trunk.html). If you want I can do this, including yourself as a full-rights contributor on the trunk service, ownership can be transferred at any time.

### CODE REVIEW

**Comment by msmollin** [comment]
Any particular reason for the rather aggressive iOS / OS X deployment targets? Putting in a deployment target requirement of iOS 10.1 / macOS 10.12 is going to make adoption of this  impossible for most applications.

**Comment by Ashton-W** [comment]
They match the deployment targets in Xcode

**Comment by msmollin** [comment]
Hmmm seeing that now. Looks like the deployment target for macOS at the project level is set to 10.10, but the individual targets are at 10.12 and iOS 10.1.

@mattgallagher any reason to not drop this back to iOS 8 and OS X 10.10 both here and in the project?

**Comment by mattgallagher** [comment]
I've dropped the deployment target to iOS 8 and macOS 10.10. I'm still working on sorting out issues with package systems. I've started with Swift Package Manager but CocoaPods is up next.

**Comment by mattgallagher** [comment]
It's been a while but I've finally performed the numerous tidy ups on this project's build processes that I wanted to perform and building through Cocoapods is part of that.

**Comment by msmollin** [comment]
Woo thank you sir.

**Pull request merged**
